#!/bin/sh

for fpid in $(pgrep -f libflashplayer.so); do
	for ftmp in /proc/$fpid/fd/*; do
		TARGET=$(readlink $ftmp);
		#echo $TARGET
		FNAME=${TARGET}
		FNAME=${FNAME#/tmp/FlashXX}
		if [ "$FNAME" = "$TARGET" ]; then continue; fi
		FNAME=${FNAME% (deleted)}
		if [ "$FNAME" = "$TARGET" ]; then continue; fi
		echo "FlashXX$FNAME -> $ftmp"
		cp -aH "$ftmp" "FlashXX$FNAME"
	done
done
