#!/bin/sh
# Reveals location of streamed flash content

MINMTIME=300
MINFSIZE=1048576

while getopts 't:s:' o; do
	case $o in
	t )	MINMTIME="$OPTARG";;
	s )	MINFSIZE="$OPTARG";;
	\? )	echo "$USAGE"; exit 2;;
	esac
done
shift $(expr $OPTIND - 1)

for fpid in $(pgrep -f 'firefox|libflashplayer.so|libpepflashplayer.so|chromium' | sort -u); do
	fdir=/proc/$fpid/fd
	msudo=$(test -x $fdir && echo || echo sudo)
	for ftmp in $($msudo ls -1 $fdir); do
		ftmp=$fdir/$ftmp
		TARGET=$($msudo readlink $ftmp);
		FNAME="${TARGET}"
		FNAME="${FNAME% (deleted)}"
		if [ "$FNAME" = "$TARGET" ]; then continue; fi
		TARGET="${FNAME}"

		FNAME="${FNAME#/tmp/FlashXX}" # old adobe flash player naming convention
		if [ "$FNAME" = "$TARGET" ]; then
			# pepper flash player naming convention
			if [ "$(basename "$(dirname "$FNAME")")" = "Shockwave Flash" ]; then
				FNAME="$(basename "$FNAME")"
				FNAME="${FNAME#.org.chromium.Chromium.}"
			else
				continue
			fi
		fi

		SINCE="$(expr $(date +%s) - $($msudo date +%s -r "$ftmp"))"
		SIZE="$($msudo stat -L -c %s "$ftmp")"
		if ! [ "$SINCE" -ge "$MINMTIME" -a "$SIZE" -ge "$MINFSIZE" ]; then continue; fi
		COPYNAME="FlashXX$FNAME"
		echo ">>> $ftmp"
		while true; do
			echo "copy $ftmp => $COPYNAME"
			read -p  "[Y]es, [n]o, [p]review, [v]iew-and-skip, or type an alternative name: " x
			case "$x" in
			y|"" )	$msudo cp -iL "$ftmp" "$COPYNAME"; chmod 644 "$COPYNAME"; break;;
			n )	break;;
			p )	totem "$ftmp";;
			v )	totem "$ftmp"; break;;
			* )	COPYNAME="$(echo "$x" | sed -e 's|/|__|g')";;
			esac
		done
	done
done
