#!/bin/sh
# Extract text from VTT subtitle file; very hacky.
# Works OK-ish for youtube autogenerated subtitles.

cat "$1" \
  | grep -v 'align:start' \
  | grep -v '^$' \
  | grep -v '^ $' \
  | sed -e 's/<[^>]*>//g' \
  | uniq
