#!/bin/sh
# Quick way to select your user.email if you have multiple of them.
# Requires dialog(1).

set -e
GNUPGBIN="${GNUPGBIN:-gpg}"

signingkey="$(git config user.signingkey)"
test -n "$signingkey" || { echo >&2 "abort: no git config for user.signingkey"; exit 1; }

emails="$($GNUPGBIN --with-colons -k "$signingkey" | grep uid:u | cut -d: -f10 | sed -re 's/.*<(.*)>.*/\1 \1/g')"
test -n "$signingkey" || { echo >&2 "abort: no gpg emails for $signingkey"; exit 1; }

exec 3>&1; email="$(dialog --output-fd 4 --no-tags \
--title "Select a value for user.email" --default-item "$(git config user.email)" \
--menu "Emails for key $signingkey" 24 80 20 $emails 4>&1 >&3)"

test -n "$email" && git config user.email "$email"
