#!/bin/sh
# rsync directories to a remote host whilst maintaining path structure.
#
# TODO(infinity0): add a show-diff option.
# unfortunately this will req something other than rsync.

USAGE="Usage: $0 -r <REMOTE> [-l <LOCAL>] <DIRECTION> [<DIR>]"
DRYRUN=false
CONFIRM=true

: "${BASE_L:=$HOME}"
while getopts r:l:nyh o; do
	case $o in
	r ) BASE_R="$OPTARG";;
	l ) BASE_L="$OPTARG";;
	n ) DRYRUN=true;;
	y ) CONFIRM=false;;
	h )
		cat <<-EOF
		$USAGE

		rsync directories to a remote host whilst maintaining path structure.

		Arguments:
		DIRECTION           Up = sync local to remote; Down = sync remote to local.
		DIR                 Directory to sync. If \$DIR = \$LOCAL/\$RELATIVE,
		                    then \$DIR will be synced to/from \$REMOTE/\$RELATIVE.

		Options:
		  -r REMOTE         Path to remote base dir, in the form accepted by ssh(1).
		  -l LOCAL          Path to local base dir, \$HOME by default.
		  -n                Print the command to be run, rather than running it.
		  -y                Skip confirmation request.
		  -h                This help text.
		EOF
		exit 1
		;;
	\? ) echo $USAGE; exit 1;;
	esac
done
shift `expr $OPTIND - 1`

abort() { echo >&2 "$2"; exit $1; }
abspath() { cd "$1"; pwd; cd "$OLDPWD"; }
rrsync() {
	if $DRYRUN; then
		echo "${PS4}rsync $@"
		return
	fi
	if $CONFIRM; then
		rsync -n "$@" 2>&1 | less
		read -p "Execute this run? [y/N] " x
		test "$x" = "y" || return 1
	fi
	rsync "$@"
}

DIREC="$1"
shift

case "$DIREC" in
u|up);;
d|down);;
*)
	abort 2 "specify a direction, up or down."
	;;
esac

test -n "$BASE_R" || abort 2 "no remote selected; use -r or BASE_R="
test -n "$*" || abort 2 "no paths selected"

for D in "$@"; do

# resolve path
if ! test -d "$D"; then
	if ! test -d "$BASE_L/$D"; then
		abort 2 "not a directory: $D or $BASE_L/$D"
	else
		D="$BASE_L/$D"
	fi
fi
D="$(abspath "${D:-.}")"
test "${D#$BASE_L/}" != "$D" || abort 2 "not under local base $BASE_L: $D"

# resolve direction
case "$DIREC" in
u|up)
	SRC="${D}/"
	DST="$BASE_R/${D#$BASE_L/}/"
	;;
d|down)
	SRC="$BASE_R/${D#$BASE_L/}/"
	DST="${D}/"
	;;
esac

# execute sync
rrsync -avxz --no-g --no-o --delete --update "$SRC" "$DST"

done
