#!/bin/sh

USAGE="Usage: $0 <local base> <remote url> <max % change>"
abort() { local x="$1"; shift; echo >&2 "$@"; exit $x; }
test -n "$3" || abort 2 "$USAGE"
test -f "$1" || abort 3 "File does not exist: $1"

NAGIOS_HOME="${NAGIOS_HOME:-/usr/lib/nagios}"
test -d "$NAGIOS_HOME" || abort 1 "NAGIOS_HOME not valid: $NAGIOS_HOME"
. "$NAGIOS_HOME/plugins/utils.sh"

tmp=$(mktemp --tmpdir check_urldiff-XXXXXXXX)
cleanup() { rm -f "$tmp"; }
trap 'x=$?; cleanup; trap - EXIT; echo $x' EXIT HUP INT QUIT PIPE TERM

if ! torsocks wget --quiet "$2" -U "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" -O "$tmp"; then
	echo "UNKNOWN - could not retrieve $2"
	exit "$STATE_UNKNOWN"
fi

for i in "$1" "$1".*; do
	x="$(wdiff -123s "$i" "$tmp" | grep -o -P "([0-9]+)% \w+ed" | cut -d% -f1 | paste -sd+ | bc)"
	if [ "$x" -lt "$3" ]; then
		echo "OK - $2 - $x% changed"
		exit "$STATE_OK"
	fi
done

echo "CRITICAL - $2 - $x% changed"
#trap - EXIT # don't clean up
exit "$STATE_CRITICAL"
