#!/bin/sh

USAGE="Usage: $0 <local base> <remote url> <max % change>"
abort() { local x="$1"; shift; echo >&2 "$@"; exit $x; }
test -n "$3" || abort 2 "$USAGE"
test -f "$1" || abort 3 "File does not exist: $1"

NAGIOS_HOME="${NAGIOS_HOME:-/usr/lib/nagios}"
test -d "$NAGIOS_HOME" || abort 1 "NAGIOS_HOME not valid: $NAGIOS_HOME"
. "$NAGIOS_HOME/plugins/utils.sh"

tmp=$(mktemp --tmpdir check_urldiff-XXXXXXXX)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

if ! wget --quiet "$2" -O "$tmp"; then
	echo "UNKNOWN - could not retrieve $2"
	exit "$STATE_UNKNOWN"
fi

x="$(wdiff -123s "$1" "$tmp" | grep -o -P "([0-9]+)% \w+ed" | cut -d% -f1 | paste -sd+ | bc)"
if [ "$x" -lt "$3" ]; then
	echo "OK - $2 - $x% changed"
	exit "$STATE_OK"
else
	echo "CRITICAL - $2 - $x% changed"
	exit "$STATE_CRITICAL"
fi
