#!/bin/sh

USAGE="Usage: $0 <local base> <remote url> <max % change>"
test -n "$3" || { echo >&2 "$USAGE"; exit 2; }
test -f "$1" || { echo >&2 "File does not exist: $1"; exit 3; }

NAGIOS_HOME="${NAGIOS_HOME:-/usr/lib/nagios}"
test -d "$NAGIOS_HOME" || abort 1 "NAGIOS_HOME not valid: $NAGIOS_HOME"
. "$NAGIOS_HOME/plugins/utils.sh"

tmp=$(mktemp --tmpdir check_urldiff-XXXXXXXX)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

if ! wget --quiet "$2" -O "$tmp"; then
	echo "UNKNOWN - could not retrieve $2"
	exit "$STATE_UNKNOWN"
fi

x="$(wdiff -123s "$1" "$tmp" | grep -o -P "([0-9]+)% \w+ed" | cut -d% -f1 | paste -sd+ | bc)"
if [ "$x" -lt "$3" ]; then
	echo "OK - $x% changed"
	exit "$STATE_OK"
else
	echo "CRITICAL - $x% changed"
	exit "$STATE_CRITICAL"
fi
