#!/bin/sh
# Run a command at intervals, first refreshing credentials to ssh-agent.

if [ -z "$3" ]; then echo "Usage: $0 [ID_FILE] [INTERVAL] [COMMAND] [ARGS]"; exit 2; fi

ID_FILE="$1"
INTERVAL="$2"
shift 2

expr "$INTERVAL" + 0 > /dev/null || exit 1
if [ "$INTERVAL" -le 0 ]; then sleep "$INTERVAL"; exit 1; fi

if [ ! -S "$SSH_AUTH_SOCK" ]; then
	eval $(ssh-agent)
	trap 'x=$?; ssh-agent -k; trap - EXIT; echo $x' EXIT HUP INT QUIT PIPE TERM
fi

ssh-add "$ID_FILE" || exit 1
while true; do "$@"; sleep "$INTERVAL" & wait $!; done
# sleep & wait allows more timely signal catching
